import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideChat from "./components/SideChat";

export const metadata: Metadata = {
  title: "Sample list app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 p-3 md:p-10">{children}</body>
      <SideChat />
    </html>
  );
}
